"""itaú e santander

Revision ID: cdc4124d4ad1
Revises: 23372f6d90cd
Create Date: 2022-05-03 09:44:14.173152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc4124d4ad1'
down_revision = '23372f6d90cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulacao', sa.Column('valor_entrada', sa.Float(precision=2, asdecimal=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulacao', 'valor_entrada')
    # ### end Alembic commands ###
