"""Alterações pra aceitar simulação Bradesco.

Revision ID: 23372f6d90cd
Revises: fb470bee4a69
Create Date: 2022-04-27 16:24:05.893178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23372f6d90cd'
down_revision = 'fb470bee4a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('data_nasc_conjuge', sa.Date(), nullable=True))
    op.add_column('simulacao', sa.Column('banco', sa.Integer(), nullable=True))
    op.add_column('simulacao', sa.Column('tipo_financiamento_bradesco', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulacao', 'tipo_financiamento_bradesco')
    op.drop_column('simulacao', 'banco')
    op.drop_column('pessoa', 'data_nasc_conjuge')
    # ### end Alembic commands ###
